Add DwC-A script and temporary tree coordinates data
LTER-LIFE/VeluweProtoDT pull request #24
Opened 2023-12-01 16:06 UTC by CherineJ

2023-12-02 15:51 UTC, StefanVriend commented
A general takeaway from this is that we can write a little document in which we outline our coding house style/conventions and best practices, potentially including:

- little metadata blurb (title, author, date) at the top of the script
- loading all used packages in the first section of the script
- use of `package::function()`
- explicitly calling all arguments in a function (e.g., `dbplyr::in_catalog(catalog = "AnE_Budburst", schema = "dbo", table = "tbl_Area")`)
- including checks/tests

2023-12-02 15:54 UTC, StefanVriend requested changes
Great job! Here are my thoughts and suggestions. There's only a few places where I think we can be more clear or do something more robustly. It goes without saying that I am happy to discuss any of these things in more detail or elaborate if things are unclear.

2023-12-02 15:54 UTC, StefanVriend commented on R/DwC_A_budburst.R
> +  collect()
To make sure that the list of packages at the top are complete and do not contain not-used packages, and to be fully transparent where functions come from, it is useful to use the full format (i.e., `package::function()`) for each function. The only exception are functions that belong to the `base` package, such as `mean()`.

```suggestion
d_Area <- dplyr::bl(con, dbplyr::in_catalog("AnE_Budburst", "dbo", "tbl_Area")) %>%
  dbplyr::collect() 
```

2023-12-02 15:54 UTC, StefanVriend commented on R/DwC_A_budburst.R
> +library(dplyr)
Included as part of `library(tidyverse)`
```suggestion
```

2023-12-02 15:54 UTC, StefanVriend commented on R/DwC_A_budburst.R
> +
For sake of completion, at missing packages, such as:
 ```
library(DBI)
library(odbc)
library(rstudioapi)
```

2023-12-02 15:54 UTC, StefanVriend commented on R/DwC_A_budburst.R
> +         Latitude = ifelse(AreaID == 11, Latitude.y, Latitude.x))
Maybe it would be clearer if `Longitude.y` and `Longitude.x` are named `Longitude_new` and `Longitude_old` or something similar.

2023-12-02 15:54 UTC, StefanVriend commented on R/DwC_A_budburst.R
> +unique(d_bb$Area)
What is this code for? If it is a check, it would be good to add to the comment in line 65 what the expected output of line 66 is.

2023-12-02 15:54 UTC, StefanVriend commented on R/DwC_A_budburst.R
> +  mutate('eventID_L3' = paste(eventID_L2, TreeID, sep = '_'))
Maybe for sake of clarity these lines of code can be added into the pipe of lines 70-76.

2023-12-02 15:54 UTC, StefanVriend commented on R/DwC_A_budburst.R
> +# and level 2 (level 1 ID + day of year)
Maybe it would be helpful here to write the expected for each ID level?

2023-12-02 15:54 UTC, StefanVriend commented on R/DwC_A_budburst.R
> +
It would be good here to validate whether the created DwC-A is indeed as expected using that package that you found.

2023-12-02 15:54 UTC, StefanVriend commented on R/DwC_A_budburst.R
> +library(zip)
It's best practice to add all required packages in a single script at the top of that script, so I suggest moving line 403 to the top where the other packages are loaded.

2023-12-02 15:54 UTC, StefanVriend commented on R/DwC_A_budburst.R
> +  rbind(d_ev1, d_ev2, d_ev3) %>%
To stay consistent with the use of tidyverse throughout most of the script, we can use `dplyr::bind_rows()` instead of `rbind()`

```suggestion
  dplyr::bind_rows(d_ev1, d_ev2, d_ev3) %>%
```

2023-12-02 15:54 UTC, StefanVriend commented on R/DwC_A_budburst.R
> +d_tree$AreaAbr <- d_Area$AreaShortName [match(d_tree$AreaID, d_Area$AreaID)]
I think it would be nice to use a single style for the same operation. So instead of `match()`, you could use the tidyverse equivalent of `dplyr::left_join()` like you did in line 61.
```suggestion
d_tree <- d_tree %>%
   dplyr::left_join(d_Area %>% dplyr::select('AreaID', 'AreaName', 'AreaAbr' = 'AreaShortName'), by = 'AreaID')
```

2023-12-02 15:54 UTC, StefanVriend commented on R/DwC_A_budburst.R
> +event$verbatimLocality <- sub('Hoge_Veluwe', 'Hoge Veluwe', event$verbatimLocality)
In tidyverse, this would look like:
```suggestion
event <- event %>%
   dplyr::mutate(verbatimLocality = stringr::str_replace(string = verbatimLocality, pattern = "_", replacement = " "))
```

2023-12-02 15:54 UTC, StefanVriend commented on R/DwC_A_budburst.R
> +  left_join(., dco, by = c('AreaID', 'SiteNumber', 'TreeNumber')) %>%
The first argument is always assumed to be the object called before the pipe operator, so there is no need to call `.` here in line 61. Of course, it's not wrong, just a little remark!

2023-12-02 15:54 UTC, StefanVriend commented on R/DwC_A_budburst.R
> +         Latitude = ifelse(AreaID == 11, Latitude.y, Latitude.x))
In addition, `dplyr::if_else()` is more robust in a `dplyr::mutate()` than the base `ifelse()`. Even though this works just fine, I tend to use `dplyr::if_else()` as a default.

2023-12-02 15:54 UTC, StefanVriend commented on R/DwC_A_budburst.R
> +unique(d_bb$Area)
Or we could think of a way to write this as a 'formal' check.

2023-12-02 15:54 UTC, StefanVriend commented on R/DwC_A_budburst.R
> +
If you want to select the first record here, I would suggest writing:
```suggestion
QRo_id <- taxize::get_gbifid(sci = "Quercus robur", rows = 1)
```

Or, more robust would be to select the 'accepted' record, which you get by filtering using the column 'status': 
Note, the use of the function with underscore: `taxize::get_gbifid_()`
```suggestion
QRo_id <- taxize::get_gbifid_(sci = "Quercus robur") %>% 
   dplyr::bind_rows() %>%
   dplyr::filter(status == "ACCEPTED") %>%
   dplyr::pull("usagekey")
```

2023-12-02 15:54 UTC, StefanVriend commented on R/DwC_A_budburst.R
> +
It's also possible to do the latter code for multiple species at once:
```
taxize::get_gbifid_(sci = c("Quercus robur", "Betula pendula")) %>%
  dplyr::bind_rows() %>%
  dplyr::filter(status == "ACCEPTED") %>%
  dplyr::pull("usagekey")
```

2023-12-02 15:54 UTC, StefanVriend commented on R/DwC_A_budburst.R
> +# Note: this information is manually gathered so far (How to change that?)
In response to your question in line 307:
When matching a scientific name to the GBIF ID, you can also select the scientific name including authorship:
```
 taxize::get_gbifid_(sci = c("Quercus robur", "Betula pendula")) %>% 
  dplyr::bind_rows() %>% 
  dplyr::filter(status == "ACCEPTED")
```
The above code will generate a data frame, where the first column (i.e., 'usagekey') contains the GBIF ID and the second column (i.e., 'scientificname') the scientific name and authorship.

2023-12-02 15:54 UTC, StefanVriend commented on R/DwC_A_budburst.R
> +
Or perhaps we want to add that as a separate script, which can then be separately containerised and used for many more data sets formatted in DwC-A!

2023-12-02 15:54 UTC, StefanVriend commented on R/DwC_A_budburst.R
> +# Note: this information is manually gathered so far (How to change that?)
So this condense piece of code does the whole trick, I guess. If it's unclear how this generates the required IDs and scientific names for all our taxa, we can have a look at this code together sometime soon.

2023-12-04 10:38 UTC, CherineJ commented on R/DwC_A_budburst.R
> +unique(d_bb$Area)
That was more for me, just a "nice-to-see" what areas we are actually talking about before creating the _verbatimLocation_ for the higher level events. But it doesn't really check anything, so I would just delete it.

2023-12-04 15:22 UTC, CherineJ commented on R/DwC_A_budburst.R
> +# and level 2 (level 1 ID + day of year)
Not sure what you mean with expected - just a concrete example for each level besides the description in the brackets?

2023-12-12 13:08 UTC, StefanVriend approved these changes
Good to go!

2023-12-12 13:09 UTC, merged